services:
  - type: web
    name: back-end-abalife
    env: node
    region: oregon
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:3000